"""Unit tests for InputFailsafe corner abort detection and setting enforcement."""

from unittest.mock import MagicMock

import pytest

from app.automation.input.errors import FailsafeAbortedError
from app.automation.input.failsafe import InputFailsafe


def test_failsafe_disabled() -> None:
    """Verify disabled failsafe does not trigger abort."""
    failsafe = InputFailsafe(enabled=False)
    failsafe.check_failsafe(pos_override=(0, 0))


def test_failsafe_automation_moving_bypass() -> None:
    """Verify failsafe bypasses check when movement is explicitly generated by automation."""
    failsafe = InputFailsafe(enabled=True)
    failsafe.check_failsafe(is_automation_moving=True, pos_override=(0, 0))


def test_failsafe_release_callback_invoked() -> None:
    """Verify release callback is invoked when failsafe triggers."""
    mock_release = MagicMock()
    failsafe = InputFailsafe(
        enabled=True, corner_threshold=10, release_callback=mock_release
    )

    with pytest.raises(FailsafeAbortedError):
        failsafe.check_failsafe(is_automation_moving=False, pos_override=(0, 0))

    mock_release.assert_called_once()
