"""Friday AI Assistant - Phase 6.3 Window Management, Desktop Control, Clipboard & Screen Inspection Engine."""

from app.automation.desktop.errors import (
    ClipboardFormatUnsupportedError,
    ClipboardSizeLimitError,
    ClipboardUnavailableError,
    DesktopError,
    FocusDeniedError,
    InvalidGeometryError,
    MonitorNotFoundError,
    ScreenCaptureFailedError,
    ScreenCaptureTimeoutError,
    VirtualDesktopUnavailableError,
    WindowClosedError,
    WindowNotFoundError,
    WorkspaceRestoreFailedError,
)
from app.automation.desktop.models import (
    ClipboardFormat,
    ClipboardResult,
    DesktopSnapshot,
    DesktopWindow,
    MonitorInfo,
    ScreenCaptureResult,
    SnapPosition,
    VirtualDesktopInfo,
    WindowLayoutEntry,
    WindowOperationResult,
    WindowState,
    WorkspaceLayout,
)

__all__ = [
    "ClipboardFormat",
    "ClipboardFormatUnsupportedError",
    "ClipboardResult",
    "ClipboardSizeLimitError",
    "ClipboardUnavailableError",
    "DesktopError",
    "DesktopSnapshot",
    "DesktopWindow",
    "FocusDeniedError",
    "InvalidGeometryError",
    "MonitorInfo",
    "MonitorNotFoundError",
    "ScreenCaptureFailedError",
    "ScreenCaptureResult",
    "ScreenCaptureTimeoutError",
    "SnapPosition",
    "VirtualDesktopInfo",
    "VirtualDesktopUnavailableError",
    "WindowClosedError",
    "WindowLayoutEntry",
    "WindowNotFoundError",
    "WindowOperationResult",
    "WindowState",
    "WorkspaceLayout",
    "WorkspaceRestoreFailedError",
]
