"""Domain models and data structures for AI Orchestrator & Reasoning Engine.

Phase 4.2 - AI Orchestrator & Reasoning Workflow Engine
"""

import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

from app.ai.models.models import ChatMessage


class OrchestratorState(str, Enum):
    """Lifecycle state machine states for AI Orchestrator."""

    IDLE = "IDLE"
    ANALYZING = "ANALYZING"
    PLANNING = "PLANNING"
    EXECUTING_TOOLS = "EXECUTING_TOOLS"
    SYNTHESIZING = "SYNTHESIZING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class OrchestrationStepType(str, Enum):
    """Classification of orchestration execution steps."""

    THINKING = "THINKING"
    TOOL_CALL = "TOOL_CALL"
    TOOL_RESULT = "TOOL_RESULT"
    FINAL_RESPONSE = "FINAL_RESPONSE"


@dataclass
class ToolPlanStep:
    """Structured step in an action plan calling a tool."""

    step_number: int
    tool_name: str
    arguments: dict[str, Any] = field(default_factory=dict)
    reasoning: str = ""
    status: str = "PENDING"
    result: dict[str, Any] | None = None


@dataclass
class ActionPlan:
    """Multi-step action plan generated by Orchestrator."""

    plan_id: str
    user_request: str
    steps: list[ToolPlanStep] = field(default_factory=list)
    required_tools: list[str] = field(default_factory=list)
    created_at: float = field(default_factory=time.time)


@dataclass
class OrchestrationRequest:
    """Structured request sent to AI Orchestrator."""

    request_id: str
    user_input: str
    session_id: str = ""
    messages: list[ChatMessage] = field(default_factory=list)
    context_snapshot: Any | None = None
    max_steps: int = 5
    allow_tool_execution: bool = True
    timestamp: float = field(default_factory=time.time)


@dataclass
class OrchestrationResult:
    """Structured outcome returned by AI Orchestrator."""

    request_id: str
    final_response: str = ""
    success: bool = True
    plan: ActionPlan | None = None
    executed_tools: list[dict[str, Any]] = field(default_factory=list)
    turns_taken: int = 1
    total_duration_ms: float = 0.0
    error: str | None = None
    timestamp: float = field(default_factory=time.time)


@dataclass
class OrchestratorConfiguration:
    """Configuration settings for AI Orchestrator."""

    enabled: bool = True
    max_steps: int = 5
    allow_tools: bool = True
    system_prompt_style: str = "DEFAULT"
