"""Physical user input override and interruption detector."""

import sys
from collections.abc import Callable

from app.automation.input.errors import InputInterruptedError
from app.logging import logger

try:
    import win32api

    PYWIN32_AVAILABLE = True
except ImportError:
    PYWIN32_AVAILABLE = False


class InterruptionMonitor:
    """Monitors Windows physical input state to detect user override during active automation."""

    def __init__(
        self,
        enabled: bool = True,
        movement_threshold: int = 10,
        release_callback: Callable[[], None] | None = None,
    ) -> None:
        self.enabled = enabled
        self.movement_threshold = movement_threshold
        self.release_callback = release_callback

        self._last_cursor_pos: tuple[int, int] | None = None
        self._automation_active: bool = False
        self._expected_cursor_pos: tuple[int, int] | None = None

    def start_monitoring(self) -> None:
        """Flag start of automation sequence monitoring."""
        self._automation_active = True
        if sys.platform == "win32" and PYWIN32_AVAILABLE:
            try:
                self._last_cursor_pos = win32api.GetCursorPos()
            except Exception:
                self._last_cursor_pos = None

    def stop_monitoring(self) -> None:
        """Flag end of automation sequence monitoring."""
        self._automation_active = False
        self._last_cursor_pos = None
        self._expected_cursor_pos = None

    def update_expected_position(self, x: int, y: int) -> None:
        """Register expected cursor coordinate generated by automation."""
        self._expected_cursor_pos = (x, y)
        self._last_cursor_pos = (x, y)

    def check_interruption(self) -> None:
        """Check if physical mouse or keyboard user input has interrupted active automation."""
        if not self.enabled or not self._automation_active:
            return

        if sys.platform != "win32" or not PYWIN32_AVAILABLE:
            return

        try:
            current_pos = win32api.GetCursorPos()
            if self._last_cursor_pos is not None:
                dx = abs(current_pos[0] - self._last_cursor_pos[0])
                dy = abs(current_pos[1] - self._last_cursor_pos[1])

                # Check if mouse moved beyond tolerance without automation expectation
                if dx > self.movement_threshold or dy > self.movement_threshold:
                    if self._expected_cursor_pos is not None:
                        exp_dx = abs(current_pos[0] - self._expected_cursor_pos[0])
                        exp_dy = abs(current_pos[1] - self._expected_cursor_pos[1])
                        if (
                            exp_dx <= self.movement_threshold
                            and exp_dy <= self.movement_threshold
                        ):
                            self._last_cursor_pos = current_pos
                            return

                    logger.warning(
                        "Physical mouse movement detected during active automation! Interupting."
                    )
                    self._trigger_interruption(interruption_type="MOUSE_INTERRUPT")

            self._last_cursor_pos = current_pos

            # Check physical keyboard key states for physical override (VK codes 0x08 to 0xFE)
            # Exclude mouse buttons (VK 0x01, 0x02, 0x04) which are handled above
            for vk in (
                0x0D,
                0x1B,
                0x20,
                0x41,
                0x53,
            ):  # Enter, Esc, Space, A, S sample key checks
                state = win32api.GetAsyncKeyState(vk)
                # Bit 15 set indicates key is currently down
                if state & 0x8000:
                    logger.warning(
                        "Physical keyboard interaction detected during active automation! Interrupting."
                    )
                    self._trigger_interruption(interruption_type="KEYBOARD_INTERRUPT")

        except InputInterruptedError:
            raise
        except Exception as exc:
            logger.debug(f"Interruption check error: {exc}")

    def _trigger_interruption(self, interruption_type: str) -> None:
        """Handle physical user interruption event."""
        if self.release_callback:
            try:
                self.release_callback()
            except Exception as exc:
                logger.error(f"Interruption release callback error: {exc}")

        self.stop_monitoring()
        raise InputInterruptedError(
            f"Automation interrupted by physical user input ({interruption_type}).",
            details={"interruption_type": interruption_type},
        )
